### ISSUE TITLE
Drop-down list

### ISSUE THREAD

**Issue by kastamas** [temansky/barter#5]
Когда я попробовал реализовать выпадающий список для поля 'регион', оказалась что есть определенные проблемы. 
1. Поиск работает по значению в 'value'. А в 'value' находится 'id' региона.
2. Поиск работает с первого символа, что тоже не очень удобно. 
3. Такая реализация поиска регистрозависимая. 

Что я предлагаю -> Нужно поискать варианты реализации в интернетике, и потом либо интегрировать найденное, либо написать что-то своё на основе найденного. 
ссылка на сам тег: http://htmlbook.ru/html/datalist

**Comment by temansky** [comment]
https://github.com/temansky/barter/commit/fbebeeb2b9e9ce408db3a13af91b181c2900d0ef
